### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Dajkwen** [andruhon/AndroidReadXLSX#5]
I can run your example successfully, but when i build a demo like your example,it throws exceptions.

this is my module build.gradle:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

```
defaultConfig {
    applicationId "com.best.dianjia.poitest"
    minSdkVersion 19
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
    multiDexEnabled true
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
packagingOptions {
    exclude 'META-INF/DEPENDENCIES'
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/NOTICE.txt'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/LICENSE.txt'
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:multidex:1.0.0'
}

and this is the exceptions:

org.apache.poi.POIXMLException: java.lang.reflect.InvocationTargetException
05-18 07:53:26.730 13068-13068/? W/System.err:     at org.apache.poi.xssf.usermodel.XSSFFactory.createDocumentPart(XSSFFactory.java:62)
05-18 07:53:26.730 13068-13068/? W/System.err:     at org.apache.poi.POIXMLDocumentPart.read(POIXMLDocumentPart.java:426)
05-18 07:53:26.730 13068-13068/? W/System.err:     at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:155)
05-18 07:53:26.730 13068-13068/? W/System.err:     at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:221)
05-18 07:53:26.740 13068-13068/? W/System.err:     at com.best.dianjia.poitest.MainActivity.readExcel(MainActivity.java:41)
05-18 07:53:26.740 13068-13068/? W/System.err:     at com.best.dianjia.poitest.MainActivity.access$000(MainActivity.java:20)
05-18 07:53:26.740 13068-13074/? D/dalvikvm: Debugger has detached; object registry had 4768 entries
05-18 07:53:26.740 13068-13068/? W/System.err:     at com.best.dianjia.poitest.MainActivity$1.onClick(MainActivity.java:32)
05-18 07:53:26.740 13068-13068/? W/System.err:     at android.view.View.performClick(View.java:4424)
05-18 07:53:26.740 13068-13068/? W/System.err:     at android.view.View$PerformClick.run(View.java:18383)
05-18 07:53:26.740 13068-13068/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
05-18 07:53:26.740 13068-13068/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-18 07:53:26.740 13068-13068/? W/System.err:     at android.os.Looper.loop(Looper.java:137)
05-18 07:53:26.740 13068-13068/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4998)
05-18 07:53:26.740 13068-13068/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
05-18 07:53:26.740 13068-13068/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
05-18 07:53:26.740 13068-13068/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
05-18 07:53:26.740 13068-13068/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
05-18 07:53:26.740 13068-13068/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
05-18 07:53:26.740 13068-13068/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
05-18 07:53:26.740 13068-13068/? W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
05-18 07:53:26.740 13068-13068/? W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
05-18 07:53:26.740 13068-13068/? W/System.err:     at org.apache.poi.xssf.usermodel.XSSFFactory.createDocumentPart(XSSFFactory.java:60)
05-18 07:53:26.740 13068-13068/? W/System.err:  ... 17 more
05-18 07:53:26.740 13068-13068/? W/System.err: Caused by: java.lang.NoClassDefFoundError: org/openxmlformats/schemas/drawingml/x2006/main/ThemeDocument
05-18 07:53:26.740 13068-13068/? W/System.err:     at org.openxmlformats.schemas.drawingml.x2006.main.ThemeDocument$Factory.parse(Unknown Source)
05-18 07:53:26.740 13068-13068/? W/System.err:     at org.apache.poi.xssf.model.ThemesTable.<init>(ThemesTable.java:44)
05-18 07:53:26.740 13068-13068/? W/System.err:  ... 20 more`

i don't know what i missed. hope you can help me.

**Comment by andruhon** [comment]
Hi! It will not work with appcompat. The whole app should contain less than 65k methods.

**Comment by Dajkwen** [comment]
i have to use jxl-2.6.jar for instead, and read *.xls files. 
also thanks.
