### ISSUE TITLE
issue by adding  jar files

### ISSUE THREAD

**Issue by NainalChauhan** [andruhon/AndroidReadXLSX#6]
After including the two jar files:-
aa-poi-3.10-min-0.1.5.jar 
aa-poi-ooxml-schemas-3.10-reduced-more-0.1.5.jar

I am getting the below error in Android:-
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err: org.apache.poi.POIXMLException: java.lang.reflect.InvocationTargetException
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at org.apache.poi.xssf.usermodel.XSSFFactory.createDocumentPart(XSSFFactory.java:62)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at org.apache.poi.POIXMLDocumentPart.read(POIXMLDocumentPart.java:426)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:155)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:221)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at com.exceltopdf.MainActivity.onReadClick(MainActivity.java:51)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at com.exceltopdf.MainActivity.onCreate(MainActivity.java:40)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.app.Activity.performCreate(Activity.java:5058)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2174)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.app.ActivityThread.access$700(ActivityThread.java:141)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.os.Looper.loop(Looper.java:137)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5059)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at dalvik.system.NativeStart.main(Native Method)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err: Caused by: java.lang.reflect.InvocationTargetException
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at org.apache.poi.xssf.usermodel.XSSFFactory.createDocumentPart(XSSFFactory.java:60)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err: 	... 19 more
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err: Caused by: java.lang.NoClassDefFoundError: org.openxmlformats.schemas.spreadsheetml.x2006.main.StyleSheetDocument$Factory
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at org.apache.poi.xssf.model.StylesTable.readFrom(StylesTable.java:110)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err:     at org.apache.poi.xssf.model.StylesTable.<init>(StylesTable.java:81)
04-05 15:23:38.663 7046-7046/com.exceltopdf W/System.err: 	... 22 more

Can I  have new packed jar files of version poi_3.15

**Comment by andruhon** [comment]
I didn't really try 3.15 on Android. Not sure if it is possible to make it work. Did you do all the workarounds as described in the readme?
